FROM node:lts-alpine AS packages
WORKDIR /darywin/packages

COPY ./packages /darywin/packages

# Install dependencies for all internal packages
RUN set -e && \
  find ./ -mindepth 1 -maxdepth 1 -type d \
  -exec sh -c 'for dir; do \
    if [ -f "$dir/package.json" ]; then \
      echo "Installing dependencies in $dir"; \
      npm --prefix "$dir" install; \
    fi; \
  done' _ {} +


FROM node:lts-alpine AS build

WORKDIR /darywin/backend

COPY ./backend/package*.json ./

RUN npm install --force && \
    npm cache clean --force

FROM node:lts-alpine
WORKDIR /darywin/backend

COPY --from=build /darywin/backend/node_modules ./node_modules

COPY --from=packages /darywin/packages /darywin/packages

COPY ./backend ./
COPY ./backend/.env.docker .env

EXPOSE 4004

CMD ["npm", "run", "dev:setup"]
