FROM node:lts-alpine AS packages
WORKDIR /darywin/packages

COPY ./packages /darywin/packages

# Install dependencies for all internal packages
RUN set -e && \
  find ./ -mindepth 1 -maxdepth 1 -type d \
  -exec sh -c 'for dir; do \
    if [ -f "$dir/package.json" ]; then \
      echo "Installing dependencies in $dir"; \
      npm --prefix "$dir" install; \
    fi; \
  done' _ {} +

FROM node:lts-alpine AS admin
WORKDIR /darywin/admin

COPY ./admin/package*.json ./
RUN npm install --force && npm cache clean --force

COPY ./admin ./ 
COPY ./admin/.env.docker .env

# Copy preinstalled internal packages
COPY --from=packages /darywin/packages /darywin/packages

EXPOSE 3003
CMD ["npm", "run", "dev:docker"]
