declare module '@env' {
    export const DW_API_HOST: string
    export const DW_DEFAULT_LANGUAGE: string
    export const DW_PAGE_SIZE: string
    export const DW_PROPERTIES_PAGE_SIZE: string
    export const DW_BOOKINGS_PAGE_SIZE: string
    export const DW_CDN_USERS: string
    export const DW_CDN_PROPERTIES: string
    export const DW_AGENCY_IMAGE_WIDTH: string
    export const DW_AGENCY_IMAGE_HEIGHT: string
    export const DW_PROPERTY_IMAGE_WIDTH: string
    export const DW_PROPERTY_IMAGE_HEIGHT: string
    export const DW_MINIMUM_AGE: string
    export const DW_STRIPE_PUBLISHABLE_KEY: string
    export const DW_STRIPE_MERCHANT_IDENTIFIER: string
    export const DW_STRIPE_COUNTRY_CODE: string
    export const DW_BASE_CURRENCY: string
    export const DW_WEBSITE_NAME: string
}
