# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    environment: test
    
    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
        
    - name: Run tests
      run: |
           cd ./backend
           touch .env
           echo NODE_ENV=$NODE_ENV >> .env
           echo DW_CI=$DW_CI >> .env
           echo DW_HTTPS=$DW_HTTPS >> .env
           echo DW_DB_URI=$DW_DB_URI >> .env
           echo DW_DB_SSL=$DW_DB_SSL >> .env
           echo DW_COOKIE_SECRET=$DW_COOKIE_SECRET >> .env
           echo DW_AUTH_COOKIE_DOMAIN=$DW_AUTH_COOKIE_DOMAIN >> .env
           echo DW_JWT_SECRET=$DW_JWT_SECRET >> .env
           echo DW_JWT_EXPIRE_AT=$DW_JWT_EXPIRE_AT >> .env
           echo DW_TOKEN_EXPIRE_AT=$DW_TOKEN_EXPIRE_AT >> .env
           echo DW_SMTP_HOST=$DW_SMTP_HOST >> .env
           echo DW_SMTP_PORT=$DW_SMTP_PORT >> .env
           echo DW_SMTP_USER=$DW_SMTP_USER >> .env
           echo DW_SMTP_PASS=$DW_SMTP_PASS >> .env
           echo DW_SMTP_FROM=$DW_SMTP_FROM >> .env
           echo DW_DEFAULT_LANGUAGE=$DW_DEFAULT_LANGUAGE >> .env
           echo DW_CDN_USERS=$DW_CDN_USERS >> .env
           echo DW_CDN_TEMP_USERS=$DW_CDN_TEMP_USERS >> .env
           echo DW_CDN_PROPERTIES=$DW_CDN_PROPERTIES >> .env
           echo DW_CDN_TEMP_PROPERTIES=$DW_CDN_TEMP_PROPERTIES >> .env
           echo DW_CDN_PROPERTIES=$DW_CDN_LOCATIONS >> .env
           echo DW_CDN_TEMP_PROPERTIES=$DW_CDN_TEMP_LOCATIONS >> .env
           echo DW_ADMIN_HOST=$DW_ADMIN_HOST >> .env
           echo DW_FRONTEND_HOST=$DW_FRONTEND_HOST >> .env
           echo DW_MINIMUM_AGE=$DW_MINIMUM_AGE >> .env
           echo DW_EXPO_ACCESS_TOKEN=$DW_EXPO_ACCESS_TOKEN >> .env
           echo DW_STRIPE_SECRET_KEY=$DW_STRIPE_SECRET_KEY >> .env
           echo DW_PAYPAL_CLIENT_ID=$DW_PAYPAL_CLIENT_ID >> .env
           echo DW_PAYPAL_CLIENT_SECRET=$DW_PAYPAL_CLIENT_SECRET >> .env
           echo DW_ADMIN_EMAIL=$DW_ADMIN_EMAIL >> .env
           npm install
           npm test
      env:
        NODE_ENV: ${{ vars.NODE_ENV }}
        DW_CI: ${{ vars.DW_CI }}
        DW_HTTPS: ${{ vars.DW_HTTPS }}
        DW_DB_URI: ${{ secrets.DW_DB_URI }}
        DW_DB_SSL: ${{ vars.DW_DB_SSL }}
        DW_DB_DEBUG: ${{ vars.DW_DB_DEBUG }}
        DW_COOKIE_SECRET: ${{ secrets.DW_COOKIE_SECRET }}
        DW_AUTH_COOKIE_DOMAIN: ${{ vars.DW_AUTH_COOKIE_DOMAIN }}
        DW_JWT_SECRET: ${{ secrets.DW_JWT_SECRET }}
        DW_JWT_EXPIRE_AT: ${{ vars.DW_JWT_EXPIRE_AT }}
        DW_TOKEN_EXPIRE_AT: ${{ vars.DW_TOKEN_EXPIRE_AT }}
        DW_SMTP_HOST: ${{ secrets.DW_SMTP_HOST }}
        DW_SMTP_PORT: ${{ secrets.DW_SMTP_PORT }}
        DW_SMTP_USER: ${{ secrets.DW_SMTP_USER }}
        DW_SMTP_PASS: ${{ secrets.DW_SMTP_PASS }}
        DW_SMTP_FROM: ${{ secrets.DW_SMTP_FROM }}
        DW_DEFAULT_LANGUAGE: ${{ vars.DW_DEFAULT_LANGUAGE }}
        DW_CDN_USERS: ${{ vars.DW_CDN_USERS }}
        DW_CDN_TEMP_USERS: ${{ vars.DW_CDN_TEMP_USERS }}
        DW_CDN_PROPERTIES: ${{ vars.DW_CDN_PROPERTIES }}
        DW_CDN_TEMP_PROPERTIES: ${{ vars.DW_CDN_TEMP_PROPERTIES }}
        DW_CDN_LOCATIONS: ${{ vars.DW_CDN_LOCATIONS }}
        DW_CDN_TEMP_LOCATIONS: ${{ vars.DW_CDN_TEMP_LOCATIONS }}
        DW_ADMIN_HOST: ${{ vars.DW_ADMIN_HOST }}
        DW_FRONTEND_HOST: ${{ vars.DW_FRONTEND_HOST }}
        DW_MINIMUM_AGE: ${{ vars.DW_MINIMUM_AGE }}
        DW_EXPO_ACCESS_TOKEN: ${{ secrets.DW_EXPO_ACCESS_TOKEN }}
        DW_STRIPE_SECRET_KEY: ${{ secrets.DW_STRIPE_SECRET_KEY }}
        DW_PAYPAL_CLIENT_ID: ${{ secrets.DW_PAYPAL_CLIENT_ID }}
        DW_PAYPAL_CLIENT_SECRET: ${{ secrets.DW_PAYPAL_CLIENT_SECRET }}
        DW_ADMIN_EMAIL: ${{ vars.DW_ADMIN_EMAIL }}  

    - name: Upload coverage reports to Codecov
      id: codecov
      continue-on-error: true
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./cobertura-coverage.xml
        directory: ./backend/coverage
        # fail_ci_if_error: true
        # verbose: true

    - name: Notify Codecov Status in case of failure
      if: steps.codecov.outcome != 'success'
      uses: actions/github-script@v7
      with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'codecov-tracking',
              state: 'closed'
            });
            
            for (const issue of issues.data) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '⚠️ Codecov upload failed in workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
              });
            }
          
    - name: Upload coverage reports to Coveralls
      id: coveralls
      continue-on-error: true
      uses: coverallsapp/github-action@v2
      with:
        file: ./backend/coverage/cobertura-coverage.xml
        base-path: backend
        # fail-on-error: true
        measure: true

    - name: Notify Coveralls Status in case of failure
      if: steps.coveralls.outcome != 'success'
      uses: actions/github-script@v7
      with:
        script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'coveralls-tracking',
              state: 'closed'
            });
            
            for (const issue of issues.data) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: '⚠️ Coveralls upload failed in workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
              });
            }
